spring.application.name=ElectroPhysics
# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/online_classes
spring.datasource.username=postgres
spring.datasource.password=shashintha
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081
