spring.application.name=ElectroPhysics
# Database Connection Settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:online_classes}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${PGUSER:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${PGPASSWORD:shashintha}}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8081}

app.materials.upload-dir=uploads/materials
app.assignments.upload-dir=uploads/assignments
app.assignments.submissions-dir=uploads/assignment-submissions
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=220MB
